### ISSUE TITLE
Usable with express.js?

### ISSUE THREAD

**Issue by Aaronik** [fidm/quic#9]
Hello,

Thank you for your work! My company wants to use QUIC with node.js and express.js, and yours is one of the few libraries that attempts it. Can your library be used with express? I can see at least that the server interface is similar to that of node's native `http.Server`, and I'm allured by the possibility it might be a drop in replacement. However, I cannot get it to work. If it is feasible, I can tell you in more detail what I've tried. If not, do you know of any implementations I might be able to use?

Thanks,

Aaron

**Comment by zensh** [comment]
Sorry, the project is working in progress.

**Comment by Aaronik** [comment]
For better or for worse, I made a higher level wrapper around your project! If you like it, maybe you can mention it! Or maybe not, up to you :)

https://www.npmjs.com/package/node-quic
